/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AProposRouteImport } from './routes/a-propos'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CommunauteRouteImport } from './routes/communaute'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as RdvRouteImport } from './routes/rdv'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AuthenticatedBibliothequeRouteImport } from './routes/_authenticated/bibliotheque'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminAuteursRouteImport } from './routes/admin/auteurs'
import { Route as AdminBande_infRouteImport } from './routes/admin/bande_inf'
import { Route as AdminCategories_eRouteImport } from './routes/admin/categories_e'
import { Route as AdminCategories_pRouteImport } from './routes/admin/categories_p'
import { Route as AdminChapitresRouteImport } from './routes/admin/chapitres'
import { Route as AdminEbooksRouteImport } from './routes/admin/ebooks'
import { Route as AdminLangagesRouteImport } from './routes/admin/langages'
import { Route as AdminLecteursRouteImport } from './routes/admin/lecteurs'
import { Route as AdminPaiementsRouteImport } from './routes/admin/paiements'
import { Route as AdminPaniersRouteImport } from './routes/admin/paniers'
import { Route as AdminProjetsRouteImport } from './routes/admin/projets'
import { Route as AdminRdvRouteImport } from './routes/admin/rdv'
import { Route as AdminServicesRouteImport } from './routes/admin/services'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as EbooksIndexRouteImport } from './routes/ebooks.index'
import { Route as EbooksSlugRouteImport } from './routes/ebooks.$slug'
import { Route as AuthenticatedLectureSlugRouteImport } from './routes/_authenticated/lecture.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AProposRoute = AProposRouteImport.update({
  id: '/a-propos',
  path: '/a-propos',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunauteRoute = CommunauteRouteImport.update({
  id: '/communaute',
  path: '/communaute',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const RdvRoute = RdvRouteImport.update({
  id: '/rdv',
  path: '/rdv',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedBibliothequeRoute =
  AuthenticatedBibliothequeRouteImport.update({
    id: '/bibliotheque',
    path: '/bibliotheque',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAuteursRoute = AdminAuteursRouteImport.update({
  id: '/auteurs',
  path: '/auteurs',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminBande_infRoute = AdminBande_infRouteImport.update({
  id: '/bande_inf',
  path: '/bande_inf',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminCategories_eRoute = AdminCategories_eRouteImport.update({
  id: '/categories_e',
  path: '/categories_e',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminCategories_pRoute = AdminCategories_pRouteImport.update({
  id: '/categories_p',
  path: '/categories_p',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminChapitresRoute = AdminChapitresRouteImport.update({
  id: '/chapitres',
  path: '/chapitres',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminEbooksRoute = AdminEbooksRouteImport.update({
  id: '/ebooks',
  path: '/ebooks',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminLangagesRoute = AdminLangagesRouteImport.update({
  id: '/langages',
  path: '/langages',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminLecteursRoute = AdminLecteursRouteImport.update({
  id: '/lecteurs',
  path: '/lecteurs',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminPaiementsRoute = AdminPaiementsRouteImport.update({
  id: '/paiements',
  path: '/paiements',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminPaniersRoute = AdminPaniersRouteImport.update({
  id: '/paniers',
  path: '/paniers',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminProjetsRoute = AdminProjetsRouteImport.update({
  id: '/projets',
  path: '/projets',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminRdvRoute = AdminRdvRouteImport.update({
  id: '/rdv',
  path: '/rdv',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminServicesRoute = AdminServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => AuthRoute,
} as any)
const EbooksIndexRoute = EbooksIndexRouteImport.update({
  id: '/ebooks/',
  path: '/ebooks/',
  getParentRoute: () => rootRouteImport,
} as any)
const EbooksSlugRoute = EbooksSlugRouteImport.update({
  id: '/ebooks/$slug',
  path: '/ebooks/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedLectureSlugRoute =
  AuthenticatedLectureSlugRouteImport.update({
    id: '/lecture/$slug',
    path: '/lecture/$slug',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/a-propos': typeof AProposRoute
  '/auth': typeof AuthRouteWithChildren
  '/communaute': typeof CommunauteRoute
  '/portfolio': typeof PortfolioRoute
  '/rdv': typeof RdvRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/bibliotheque': typeof AuthenticatedBibliothequeRoute
  '/admin/auteurs': typeof AdminAuteursRoute
  '/admin/bande_inf': typeof AdminBande_infRoute
  '/admin/categories_e': typeof AdminCategories_eRoute
  '/admin/categories_p': typeof AdminCategories_pRoute
  '/admin/chapitres': typeof AdminChapitresRoute
  '/admin/ebooks': typeof AdminEbooksRoute
  '/admin/langages': typeof AdminLangagesRoute
  '/admin/lecteurs': typeof AdminLecteursRoute
  '/admin/paiements': typeof AdminPaiementsRoute
  '/admin/paniers': typeof AdminPaniersRoute
  '/admin/projets': typeof AdminProjetsRoute
  '/admin/rdv': typeof AdminRdvRoute
  '/admin/services': typeof AdminServicesRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/ebooks/$slug': typeof EbooksSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/ebooks/': typeof EbooksIndexRoute
  '/lecture/$slug': typeof AuthenticatedLectureSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/auth': typeof AuthRouteWithChildren
  '/communaute': typeof CommunauteRoute
  '/portfolio': typeof PortfolioRoute
  '/rdv': typeof RdvRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/bibliotheque': typeof AuthenticatedBibliothequeRoute
  '/admin/auteurs': typeof AdminAuteursRoute
  '/admin/bande_inf': typeof AdminBande_infRoute
  '/admin/categories_e': typeof AdminCategories_eRoute
  '/admin/categories_p': typeof AdminCategories_pRoute
  '/admin/chapitres': typeof AdminChapitresRoute
  '/admin/ebooks': typeof AdminEbooksRoute
  '/admin/langages': typeof AdminLangagesRoute
  '/admin/lecteurs': typeof AdminLecteursRoute
  '/admin/paiements': typeof AdminPaiementsRoute
  '/admin/paniers': typeof AdminPaniersRoute
  '/admin/projets': typeof AdminProjetsRoute
  '/admin/rdv': typeof AdminRdvRoute
  '/admin/services': typeof AdminServicesRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/ebooks/$slug': typeof EbooksSlugRoute
  '/admin': typeof AdminIndexRoute
  '/ebooks': typeof EbooksIndexRoute
  '/lecture/$slug': typeof AuthenticatedLectureSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/admin': typeof AdminRouteRouteWithChildren
  '/a-propos': typeof AProposRoute
  '/auth': typeof AuthRouteWithChildren
  '/communaute': typeof CommunauteRoute
  '/portfolio': typeof PortfolioRoute
  '/rdv': typeof RdvRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/bibliotheque': typeof AuthenticatedBibliothequeRoute
  '/admin/auteurs': typeof AdminAuteursRoute
  '/admin/bande_inf': typeof AdminBande_infRoute
  '/admin/categories_e': typeof AdminCategories_eRoute
  '/admin/categories_p': typeof AdminCategories_pRoute
  '/admin/chapitres': typeof AdminChapitresRoute
  '/admin/ebooks': typeof AdminEbooksRoute
  '/admin/langages': typeof AdminLangagesRoute
  '/admin/lecteurs': typeof AdminLecteursRoute
  '/admin/paiements': typeof AdminPaiementsRoute
  '/admin/paniers': typeof AdminPaniersRoute
  '/admin/projets': typeof AdminProjetsRoute
  '/admin/rdv': typeof AdminRdvRoute
  '/admin/services': typeof AdminServicesRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/ebooks/$slug': typeof EbooksSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/ebooks/': typeof EbooksIndexRoute
  '/_authenticated/lecture/$slug': typeof AuthenticatedLectureSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/a-propos'
    | '/auth'
    | '/communaute'
    | '/portfolio'
    | '/rdv'
    | '/services'
    | '/sitemap.xml'
    | '/bibliotheque'
    | '/admin/auteurs'
    | '/admin/bande_inf'
    | '/admin/categories_e'
    | '/admin/categories_p'
    | '/admin/chapitres'
    | '/admin/ebooks'
    | '/admin/langages'
    | '/admin/lecteurs'
    | '/admin/paiements'
    | '/admin/paniers'
    | '/admin/projets'
    | '/admin/rdv'
    | '/admin/services'
    | '/auth/callback'
    | '/ebooks/$slug'
    | '/admin/'
    | '/ebooks/'
    | '/lecture/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/a-propos'
    | '/auth'
    | '/communaute'
    | '/portfolio'
    | '/rdv'
    | '/services'
    | '/sitemap.xml'
    | '/bibliotheque'
    | '/admin/auteurs'
    | '/admin/bande_inf'
    | '/admin/categories_e'
    | '/admin/categories_p'
    | '/admin/chapitres'
    | '/admin/ebooks'
    | '/admin/langages'
    | '/admin/lecteurs'
    | '/admin/paiements'
    | '/admin/paniers'
    | '/admin/projets'
    | '/admin/rdv'
    | '/admin/services'
    | '/auth/callback'
    | '/ebooks/$slug'
    | '/admin'
    | '/ebooks'
    | '/lecture/$slug'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/admin'
    | '/a-propos'
    | '/auth'
    | '/communaute'
    | '/portfolio'
    | '/rdv'
    | '/services'
    | '/sitemap.xml'
    | '/_authenticated/bibliotheque'
    | '/admin/auteurs'
    | '/admin/bande_inf'
    | '/admin/categories_e'
    | '/admin/categories_p'
    | '/admin/chapitres'
    | '/admin/ebooks'
    | '/admin/langages'
    | '/admin/lecteurs'
    | '/admin/paiements'
    | '/admin/paniers'
    | '/admin/projets'
    | '/admin/rdv'
    | '/admin/services'
    | '/auth/callback'
    | '/ebooks/$slug'
    | '/admin/'
    | '/ebooks/'
    | '/_authenticated/lecture/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  AProposRoute: typeof AProposRoute
  AuthRoute: typeof AuthRouteWithChildren
  CommunauteRoute: typeof CommunauteRoute
  PortfolioRoute: typeof PortfolioRoute
  RdvRoute: typeof RdvRoute
  ServicesRoute: typeof ServicesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  EbooksSlugRoute: typeof EbooksSlugRoute
  EbooksIndexRoute: typeof EbooksIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/a-propos': {
      id: '/a-propos'
      path: '/a-propos'
      fullPath: '/a-propos'
      preLoaderRoute: typeof AProposRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/communaute': {
      id: '/communaute'
      path: '/communaute'
      fullPath: '/communaute'
      preLoaderRoute: typeof CommunauteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rdv': {
      id: '/rdv'
      path: '/rdv'
      fullPath: '/rdv'
      preLoaderRoute: typeof RdvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/bibliotheque': {
      id: '/_authenticated/bibliotheque'
      path: '/bibliotheque'
      fullPath: '/bibliotheque'
      preLoaderRoute: typeof AuthenticatedBibliothequeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/auteurs': {
      id: '/admin/auteurs'
      path: '/auteurs'
      fullPath: '/admin/auteurs'
      preLoaderRoute: typeof AdminAuteursRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/bande_inf': {
      id: '/admin/bande_inf'
      path: '/bande_inf'
      fullPath: '/admin/bande_inf'
      preLoaderRoute: typeof AdminBande_infRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/categories_e': {
      id: '/admin/categories_e'
      path: '/categories_e'
      fullPath: '/admin/categories_e'
      preLoaderRoute: typeof AdminCategories_eRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/categories_p': {
      id: '/admin/categories_p'
      path: '/categories_p'
      fullPath: '/admin/categories_p'
      preLoaderRoute: typeof AdminCategories_pRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/chapitres': {
      id: '/admin/chapitres'
      path: '/chapitres'
      fullPath: '/admin/chapitres'
      preLoaderRoute: typeof AdminChapitresRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/ebooks': {
      id: '/admin/ebooks'
      path: '/ebooks'
      fullPath: '/admin/ebooks'
      preLoaderRoute: typeof AdminEbooksRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/langages': {
      id: '/admin/langages'
      path: '/langages'
      fullPath: '/admin/langages'
      preLoaderRoute: typeof AdminLangagesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/lecteurs': {
      id: '/admin/lecteurs'
      path: '/lecteurs'
      fullPath: '/admin/lecteurs'
      preLoaderRoute: typeof AdminLecteursRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/paiements': {
      id: '/admin/paiements'
      path: '/paiements'
      fullPath: '/admin/paiements'
      preLoaderRoute: typeof AdminPaiementsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/paniers': {
      id: '/admin/paniers'
      path: '/paniers'
      fullPath: '/admin/paniers'
      preLoaderRoute: typeof AdminPaniersRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/projets': {
      id: '/admin/projets'
      path: '/projets'
      fullPath: '/admin/projets'
      preLoaderRoute: typeof AdminProjetsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/rdv': {
      id: '/admin/rdv'
      path: '/rdv'
      fullPath: '/admin/rdv'
      preLoaderRoute: typeof AdminRdvRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/services': {
      id: '/admin/services'
      path: '/services'
      fullPath: '/admin/services'
      preLoaderRoute: typeof AdminServicesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof AuthRoute
    }
    '/ebooks/': {
      id: '/ebooks/'
      path: '/ebooks'
      fullPath: '/ebooks/'
      preLoaderRoute: typeof EbooksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ebooks/$slug': {
      id: '/ebooks/$slug'
      path: '/ebooks/$slug'
      fullPath: '/ebooks/$slug'
      preLoaderRoute: typeof EbooksSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/lecture/$slug': {
      id: '/_authenticated/lecture/$slug'
      path: '/lecture/$slug'
      fullPath: '/lecture/$slug'
      preLoaderRoute: typeof AuthenticatedLectureSlugRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedBibliothequeRoute: typeof AuthenticatedBibliothequeRoute
  AuthenticatedLectureSlugRoute: typeof AuthenticatedLectureSlugRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedBibliothequeRoute: AuthenticatedBibliothequeRoute,
  AuthenticatedLectureSlugRoute: AuthenticatedLectureSlugRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AdminRouteRouteChildren {
  AdminAuteursRoute: typeof AdminAuteursRoute
  AdminBande_infRoute: typeof AdminBande_infRoute
  AdminCategories_eRoute: typeof AdminCategories_eRoute
  AdminCategories_pRoute: typeof AdminCategories_pRoute
  AdminChapitresRoute: typeof AdminChapitresRoute
  AdminEbooksRoute: typeof AdminEbooksRoute
  AdminLangagesRoute: typeof AdminLangagesRoute
  AdminLecteursRoute: typeof AdminLecteursRoute
  AdminPaiementsRoute: typeof AdminPaiementsRoute
  AdminPaniersRoute: typeof AdminPaniersRoute
  AdminProjetsRoute: typeof AdminProjetsRoute
  AdminRdvRoute: typeof AdminRdvRoute
  AdminServicesRoute: typeof AdminServicesRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminAuteursRoute: AdminAuteursRoute,
  AdminBande_infRoute: AdminBande_infRoute,
  AdminCategories_eRoute: AdminCategories_eRoute,
  AdminCategories_pRoute: AdminCategories_pRoute,
  AdminChapitresRoute: AdminChapitresRoute,
  AdminEbooksRoute: AdminEbooksRoute,
  AdminLangagesRoute: AdminLangagesRoute,
  AdminLecteursRoute: AdminLecteursRoute,
  AdminPaiementsRoute: AdminPaiementsRoute,
  AdminPaniersRoute: AdminPaniersRoute,
  AdminProjetsRoute: AdminProjetsRoute,
  AdminRdvRoute: AdminRdvRoute,
  AdminServicesRoute: AdminServicesRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface AuthRouteChildren {
  AuthCallbackRoute: typeof AuthCallbackRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthCallbackRoute: AuthCallbackRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  AProposRoute: AProposRoute,
  AuthRoute: AuthRouteWithChildren,
  CommunauteRoute: CommunauteRoute,
  PortfolioRoute: PortfolioRoute,
  RdvRoute: RdvRoute,
  ServicesRoute: ServicesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  EbooksSlugRoute: EbooksSlugRoute,
  EbooksIndexRoute: EbooksIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
